###
# Path fields
###
path-flavor-id:
  description: |
    Specifies the flavor ID.
  in: path
  required: yes
  type: uuid
path-project-id:
  description: |
    Specifies the project ID.
  in: path
  required: true
  type: string
###
# Query parameters
###
flavor-id-query:
  description: |
    Specifies the flavor ID.
    Multiple IDs can be queried in the format of id=xxx&id=xxx.
  in: query
  required: no
  type: uuid
flavor-name-query:
  description: |
    Specifies the flavor name.
    Multiple names can be queried in the format of name=xxx&name=xxx.
  in: query
  required: no
  type: string
flavor-shared-query:
  description: |
    Specifies whether the flavor is available to all users.
    **true** indicates that the flavor is available to all users.
    **false** indicates that the flavor is available only to a specific user.
  in: query
  required: no
  type: boolean

limit:
  description: |
    Specifies the number of records on each page.
    Minimum: 0
    Maximum: 2000
  in: query
  required: no
  type: integer
marker:
  description: |
    Specifies the ID of the last record on the previous page.

    Note:
      - This parameter must be used together with limit.
      - If this parameter is not specified, the first page will be queried.
      - This parameter cannot be left blank or set to an invalid ID.
  in: query
  required: no
  type: uuid
page-reverse:
  description: |
    Specifies the page direction.
    The value can be true or false, and the default value is false.
    The last page in the list requested with page_reverse set to false will not contain the "next" link, and the last page in the list requested with page_reverse set to true will not contain the "previous" link.
    This parameter must be used together with limit.
  in: query
  required: no
  type: boolean
###
# Body fields
###
flavor:
  description: |
    Specifies the flavors.
  in: body
  type: object
  required: true
flavor-id:
  description: |
    Specifies the flavor ID.
  in: body
  required: true
  type: uuid
flavor-info:
  description: |
    Specifies the flavor details.
  in: body
  required: true
  type: flavor-info
flavor-info-bandwidth:
  description: |
    Specifies the inbound and outbound bandwidth in the unit of Kbit/s.
  in: body
  required: true
  type: integer
flavor-info-connection:
  description: |
    Specifies the maximum concurrent connections.
  in: body
  required: true
  type: integer
flavor-info-cps:
  description: |
    Specifies the number of new connections per second.
  in: body
  required: true
  type: integer
flavor-info-qps:
  description: |
    Specifies the number of requests per second at Layer 7.
  in: body
  required: true
  type: integer
flavor-name:
  description: |
    Specifies the flavor name.
  in: body
  required: true
  type: string
flavor-shared:
  description: |
    Specifies whether the flavor is available to all users.
    **true** indicates that the flavor is available to all users.
    **false** indicates that the flavor is available only to a specific user.
    Default: true
  in: body
  required: true
  type: boolean
flavor-type:
  description: |
    Specifies the flavor type. Flavors can be filtered by type.
    Minimum: 1
    Maximum: 32
  in: body
  required: true
  type: string
flavors:
  description: |
    Lists the flavors.
  in: body
  type: array
  required: true
page-info:
  description: |
    Shows pagination information
  in: body
  type: array
  required: false
project-id:
  description: |
    Specifies the project ID.
  in: body
  required: true
  type: uuid
request-id:
  description: |
    Specifies the request ID. The value is automatically generated.
  in: body
  type: string
  required: true
